# Generated by Django 4.2.11 on 2024-03-25 17:39

from django.db import migrations, models
import django.db.models.deletion
import datetime

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infotech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('secondname', models.CharField(max_length=25)),
                ('mobile1', models.CharField(max_length=10)),
                ('mobile2', models.CharField(max_length=10)),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=25)),
                ('total_days', models.CharField(max_length=1)),
                ('booking_days', models.DateField()),
            ],
        ),
    ]
